import Head from "next/head";
import Banner from "../components/Banner";
import Footer from "./../components/Footer";
import Header from "./../components/Header";
import Testimonial from "../components/Testimonial";
import CTA from "../components/CTA";
import Features from "../components/Features";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Header />
        <Banner />
        <Features />
        <Testimonial />
        <CTA />
        <Footer />
      </main>
    </div>
  );
}
